language: node_js
notifications:
  email: startae14@gmail.com
node_js:
  - "stable"
install: npm install
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
before_script:
  - npm install
script:
  - npm test
  - npm run build
  - npm run validate
after_script: npx codecov@3
